version: '3'

services:
  mongo-db:
    image: mongo:6-jammy
    ports:
      - 27020:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
      MONGODB_HOST: ${MONGODB_HOST}
    volumes:
      - gomoney_mongodb:/data/db

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - '6381:6379'
    volumes:
      - gomoney_redis:/data

  # gomoney_api:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   ports:
  #     - "5000:5000"
  
volumes:
  gomoney_mongodb:
  gomoney_redis: